version: '3.8'

services:

  site_local:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "8080:80"
    env_file:
      - ./.env.local
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.local

volumes:
  db_data:
