version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
        #volumes:
        #  - static_volume:/app/django_static
        #expose:
        #  - 8000
    ports:
      - "8080:80"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

        #frontend:
        #  build:
        #    context: .
        #    dockerfile: ./docker/frontend/Dockerfile
        #  volumes:
        #    - static_volume:/usr/share/nginx/html/django_static
        #    #- /var/run/docker.sock:/tmp/docker.sock:ro
        #    #- vhost:/etc/nginx/vhost.d
        #    #- certs:/etc/nginx/certs
        #    #- html:/usr/share/nginx/html
        #  env_file:
        #    - ./.env.dev
        #  ports:
        #    - "8080:80"
        #  depends_on: 
        #    - backend

        #volumes:
        #  static_volume:
  #postgres_data:
  #certs:
  #html:
  #vhost:
  #acme:
