version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: /docker/backend/entrypoint.sh
    volumes:
      - static_volume:/app/django_static
    expose:
      - 8000
    env_file:
      - ./.env.dev

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - static_volume:/app/django_static
    ports:
      - "8080:80"
    depends_on: 
      - backend

volumes:
  static_volume: {}
