version: '3.8'

services:

  site:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  db_data:
