version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
