[tool.poetry]
name = "backend"
version = "0.1.0"
description = "A Django/React webapp."
authors = ["long"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2.5"
djangorestframework = "^3.12.4"
psycopg2-binary = "^2.9.1"
flake8 = "^3.9.2"
mypy = "^0.910"
django-cors-headers = "^3.10.0"
django-ninja = "^0.16.1"
factory-boy = "^3.2.1"
email-validator = "^1.1.3"
cryptography = "^36.0.1"
django-ninja-jwt = "^5.1.5"
django-ninja-extra = "^0.14.0"

[tool.poetry.dev-dependencies]
ipython = "^7.22.0"
neovim = "^0.3.1"
requests = "^2.25.1"
black = "^21.9b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
