#!/usr/bin/env bash

# removes all migration files
rm $(fd -I -p "migrations/\d+.*\.py")
rm debug_db.sqlite3
poetry run ./manage.py makemigrations
poetry run ./manage.py migrate
poetry run ./manage.py init_db
poetry run ./manage.py runserver
