# Generated by Django 4.0.2 on 2022-03-02 18:15

import auto_prefetch
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_timestamp", models.FloatField(default=0)),
                ("edited_at", models.DateTimeField(auto_now=True)),
                ("edited_timestamp", models.FloatField(default=0)),
                ("up", models.IntegerField(default=0)),
                ("total", models.IntegerField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("tile_1", models.CharField(max_length=200)),
                ("tile_2", models.CharField(max_length=200)),
                ("tile_3", models.CharField(max_length=200)),
                ("tile_4", models.CharField(max_length=200)),
                ("tile_5", models.CharField(max_length=200)),
                ("tile_6", models.CharField(max_length=200)),
                ("tile_7", models.CharField(max_length=200)),
                ("tile_8", models.CharField(max_length=200)),
                ("tile_9", models.CharField(max_length=200)),
                ("tile_10", models.CharField(max_length=200)),
                ("tile_11", models.CharField(max_length=200)),
                ("tile_12", models.CharField(max_length=200)),
                ("tile_13", models.CharField(max_length=200)),
                ("tile_14", models.CharField(max_length=200)),
                ("tile_15", models.CharField(max_length=200)),
                ("tile_16", models.CharField(max_length=200)),
                ("tile_17", models.CharField(max_length=200)),
                ("tile_18", models.CharField(max_length=200)),
                ("tile_19", models.CharField(max_length=200)),
                ("tile_20", models.CharField(max_length=200)),
                ("tile_21", models.CharField(max_length=200)),
                ("tile_22", models.CharField(max_length=200)),
                ("tile_23", models.CharField(max_length=200)),
                ("tile_24", models.CharField(max_length=200)),
                ("tile_25", models.CharField(max_length=200)),
                ("is_init", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "name",
                    models.CharField(max_length=49, primary_key=True, serialize=False, unique=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HashtagSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_subscribed", models.IntegerField(default=1)),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HashtagToCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("up_state", models.IntegerField(default=0)),
                ("down_state", models.IntegerField(default=0)),
                ("up", models.IntegerField()),
                (
                    "card",
                    auto_prefetch.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="card.card",
                    ),
                ),
            ],
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("prefetch_manager", django.db.models.manager.Manager()),
            ],
        ),
    ]
